services:
  api-gateway:
    build:
      context: .
      dockerfile: api-gateway/Dockerfile
    container_name: api-gateway
    restart: always
    ports:
      - "8080:8080"
    environment:
      - USER_SERVICE_URL=user-service:8081
      - SERVER_PORT=8080
      - LOG_LEVEL=INFO
    depends_on:
      - user-service
    networks:
      - app-network

  user-service:
    build:
      context: .
      dockerfile: user-service/Dockerfile
    container_name: user-service
    restart: always
    ports:
      - "8081:8081"
    environment:
      - SERVER_PORT=8081
      - REDIS_PORT=6379
      - LOG_LEVEL=INFO
    networks:
      - app-network
      - db-network

  redis:
    image: redis:latest
    container_name: user-service-redis
    ports:
      - "5432:6379"
    volumes:
      - redis-data:/data
    networks:
      - db-network

networks:
  app-network:
    driver: bridge
  db-network:
    driver: bridge

volumes:
  redis-data:
