openapi: 3.0.3
info:
  title: User Management API
  version: 1.0.0

paths:
  /users/register:
    post:
      summary: Регистрация нового пользователя
      description: Создает нового пользователя в системе
      requestBody:
        description: Данные для регистрации пользователя
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/RegisterRequest'
      responses:
        '201':
          description: Пользователь успешно зарегистрирован
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                    example: User registered successfully
                  user:
                    type: object
                    properties:
                      id:
                        type: integer
                        example: 1
                      login:
                        type: string
                        example: user123
                      email:
                        type: string
                        format: email
                        example: user@example.com
                      created_at:
                        type: string
                        format: date-time
                        example: '2023-01-15T14:30:00Z'
        '400':
          description: Некорректные данные запроса
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
        '409':
          description: Пользователь с таким логином или email уже существует
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
        '500':
          description: Внутренняя ошибка сервера
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'

  /users/login:
    post:
      summary: Аутентификация пользователя
      description: Аутентификация пользователя по логину и паролю
      requestBody:
        description: Учетные данные пользователя
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/LoginRequest'
      responses:
        '200':
          description: Аутентификация успешна
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                    example: Login successful
                  user:
                    $ref: '#/components/schemas/User'
                    
        '400':
          description: Некорректные данные запроса
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
        '401':
          description: Неверный логин или пароль
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
        '500':
          description: Внутренняя ошибка сервера
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'

  /users/profile:
    get:
      summary: Получение данных профиля пользователя
      description: Получает все данные профиля аутентифицированного пользователя
      security:
        - BearerAuth: []
      responses:
        '200':
          description: Данные профиля успешно получены
          content:
            application/json:
              schema:
                type: object
                properties:
                  user:
                    $ref: '#/components/schemas/User'
        '401':
          description: Не авторизован
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
        '500':
          description: Внутренняя ошибка сервера
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'

    put:
      summary: Обновление данных профиля пользователя
      description: Обновляет данные профиля аутентифицированного пользователя
      security:
        - BearerAuth: []
      requestBody:
        description: Данные для обновления профиля
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/UpdateProfileRequest'
      responses:
        '200':
          description: Профиль успешно обновлен
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                    example: Profile updated successfully
                  user:
                    $ref: '#/components/schemas/User'
        '400':
          description: Некорректные данные запроса
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
        '401':
          description: Не авторизован
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
        '500':
          description: Внутренняя ошибка сервера
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
  /posts:
    post:
      summary: Create a new post
      operationId: createPost
      requestBody:
        description: Post object that needs to be added to the wall
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Post'
      responses:
        '200':
          description: Post created successfully
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Post'
        '400':
          description: Invalid input
        '401':
          description: Unauthorized
        '500':
          description: Error creating post
    get:
      summary: List posts
      operationId: listPosts
      parameters:
        - in: query
          name: page_number
          schema:
            type: integer
          description: Page number for pagination
          required: false
        - in: query
          name: page_size
          schema:
            type: integer
          description: Number of posts per page
          required: false
      responses:
        '200':
          description: List of posts
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Post'
        '401':
          description: Unauthorized
        '500':
          description: Error listing posts

  /posts/{id}:
    get:
      summary: Get a specific post
      operationId: getPost
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: string
          description: ID of the post to return
      responses:
        '200':
          description: Post details
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Post'
        '401':
          description: Unauthorized
        '404':
          description: Not Found
        '500':
          description: Error fetching post
    put:
      summary: Update an existing post
      operationId: updatePost
      requestBody:
        description: Post object that needs to be updated
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Post'
      responses:
        '200':
          description: Post updated successfully
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Post'
        '400':
          description: Invalid input
        '401':
          description: Unauthorized
        '404':
          description: Not Found
        '500':
          description: Error updating post
    delete:
      summary: Delete a post
      operationId: deletePost
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: string
          description: ID of the post to delete
      responses:
        '200':
          description: Post deleted successfully
        '401':
          description: Unauthorized
        '404':
          description: Not Found
        '500':
          description: Error deleting post
  /posts/{id}/view:
    post:
      summary: Register a post view
      description: Records that the authenticated user has viewed the post
      operationId: viewPost
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: string
          description: ID of the post to view
      security:
        - BearerAuth: []
      responses:
        '200':
          description: View successfully recorded
        '401':
          description: Unauthorized
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
        '403':
          description: Forbidden to view this post
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
        '404':
          description: Post not found
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
        '500':
          description: Internal server error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'

  /posts/{id}/like:
    post:
      summary: Like a post
      description: Toggles a like on the specified post for the authenticated user
      operationId: likePost
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: string
          description: ID of the post to like
      security:
        - BearerAuth: []
      responses:
        '200':
          description: Like operation successful
        '401':
          description: Unauthorized
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
        '403':
          description: Forbidden to like this post
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
        '404':
          description: Post not found
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
        '500':
          description: Internal server error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'

  /posts/{id}/comments:
    post:
      summary: Create a new comment
      description: Adds a comment to the specified post
      operationId: createComment
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: string
          description: ID of the post to comment on
      requestBody:
        description: Comment text
        required: true
        content:
          application/json:
            schema:
              type: object
              required:
                - text
              properties:
                text:
                  type: string
                  example: "This is a great post!"
      security:
        - BearerAuth: []
      responses:
        '201':
          description: Comment created successfully
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Comment'
        '400':
          description: Invalid input
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
        '401':
          description: Unauthorized
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
        '403':
          description: Forbidden to comment on this post
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
        '404':
          description: Post not found
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
        '500':
          description: Internal server error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
    get:
      summary: List post comments
      description: Gets a paginated list of comments for the specified post
      operationId: listComments
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: string
          description: ID of the post to get comments for
        - in: query
          name: page_number
          schema:
            type: integer
            default: 1
            minimum: 1
          description: Page number for pagination
          required: false
        - in: query
          name: page_size
          schema:
            type: integer
            default: 10
            minimum: 1
            maximum: 100
          description: Number of comments per page
          required: false
      security:
        - BearerAuth: []
      responses:
        '200':
          description: List of comments
          content:
            application/json:
              schema:
                type: object
                properties:
                  comments:
                    type: array
                    items:
                      $ref: '#/components/schemas/Comment'
                  total_count:
                    type: integer
                    description: Total number of comments for this post
                    example: 42
        '401':
          description: Unauthorized
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
        '404':
          description: Post not found
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
        '500':
          description: Internal server error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'

components:
  schemas:
    RegisterRequest:
      type: object
      required:
        - login
        - password
        - email
      properties:
        login:
          type: string
          example: user123
          minLength: 3
          maxLength: 50
        password:
          type: string
          format: password
          example: securePassword123
          minLength: 8
        email:
          type: string
          format: email
          example: user@example.com

    LoginRequest:
      type: object
      required:
        - login
        - password
      properties:
        login:
          type: string
          example: user123
        password:
          type: string
          format: password
          example: securePassword123

    UpdateProfileRequest:
      type: object
      properties:
        first_name:
          type: string
          example: John
        last_name:
          type: string
          example: Doe
        birth_date:
          type: string
          format: date
          example: '1990-01-01'
        email:
          type: string
          format: email
          example: john.doe@example.com
        phone_number:
          type: string
          example: '+1234567890'
          pattern: '^\+?[0-9]{10,15}$'

    User:
      type: object
      properties:
        user_id:
          type: string
          example: 6ba7b810-9dad-11d1-80b4-00c04fd430c8
        login:
          type: string
          example: user123
        email:
          type: string
          format: email
          example: user@example.com
        first_name:
          type: string
          example: John
        last_name:
          type: string
          example: Doe
        birth_date:
          type: string
          format: date
          example: '1990-01-01'
        phone_number:
          type: string
          example: '+1234567890'
        created_at:
          type: string
          format: date-time
          example: '2023-01-15T14:30:00Z'
        updated_at:
          type: string
          format: date-time
          example: '2023-01-20T12:15:00Z'
      
      Post:
      type: object
      properties:
        post_id:
          type: string
        title:
          type: string
        description:
          type: string
        creator_id:
          type: string
        created_at:
          type: string
          format: date-time
        updated_at:
          type: string
          format: date-time
        is_private:
          type: boolean
        tags:
          type: array
          items:
            type: string

        Comment:
      type: object
      properties:
        comment_id:
          type: string
        post_id:
          type: string
        creator_id:
          type: string
        text:
          type: string
        created_at:
          type: string
          format: date-time
        updated_at:
          type: string
          format: date-time


    ErrorResponse:
      type: string
      desctiption: Plain error message

  securitySchemes:
    BearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT
